# Generated by Django 2.1.5 on 2019-11-21 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=4)),
                ('bid_amt', models.IntegerField(default=0)),
                ('bidding_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bidding_app.BiddingUser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=4)),
                ('project_description', models.CharField(max_length=100)),
                ('project_objective', models.CharField(max_length=100)),
                ('project_deliverables', models.CharField(max_length=100)),
                ('project_skills', models.CharField(max_length=100)),
                ('project_notes', models.CharField(max_length=100)),
            ],
        ),
    ]
